import thermometer from "./thermometer1.jpg";
import medicine_box from "./medicine_box2.jpg";
import bp_monitor from "./bp_monitor3.jpg";
import med_watch from "./med_watch4.jpg";
import disinfectant_wipes from "./disinfectant_wipes5.jpg";
import oxygen_concentrator from "./oxygen_concentrator6.jpg";
import first_aid_kit from "./first_aid_kit7.jpg";
import ice_pack from "./ice_pack8.jpg";
import cpr_mask from "./cpr_mask9.jpg";
import ultrasound from "./ultrasound10.jpg";
import ventilator11 from "./ventilator11.jpg";
import gloves from "./gloves12.jpg";
import defibrillator13 from "./defibrillator13.jpg";
import trauma_scissors from "./trauma_scissors14.jpg";
import stretcher15 from "./stretcher15.jpg";
import face_mask16 from "./face_mask16.jpg";
import emergency_blanket from "./emergency_blanket17.jpg";
import iv_pump18 from "./iv_pump18.jpg";
import monitoring_system19 from "./monitoring_system19.jpg";

import response_kit20 from "./response_kit20.jpg";
import wound_care_kit21 from "./wound_care_kit21.jpg";
import triage_tent22 from "./triage_tent22.jpg";
import oxygen_mask23 from "./oxygen_mask23.jpg";
import ecg_machine24 from "./ecg_machine24.jpg";
import rope25 from "./rope25.jpg";
import hoke26 from "./hoke26.jpg";
import biometric_scanner27 from "./biometric_scanner27.jpg";
import infusion_stand28 from "./infusion_stand28.jpg";
import respiratory_mask29 from "./respiratory_mask29.jpg";
import trauma_dressing30 from "./trauma_dressing30.jpg";
import fire_blanket31 from "./fire_blanket31.jpg";
import sterile_needle32 from "./sterile_needle32.jpg";
import water_purifier33 from "./water_purifier33.jpg";
import ultrasound_gel34 from "./ultrasound_gel34.jpg";
import spinal_board35 from "./spinal_board35.jpg";
import defibrillator36 from "./defibrillator36.jpg";
import trauma_bag37 from "./trauma_bag37.jpg";
import survival_tent38 from "./survival_tent38.jpg";
import blood_bag_warmer39 from "./blood_bag_warmer39.jpg";
import icePack40 from "./icePack40.jpg";



export const assets = {
  thermometer,
  medicine_box,
  bp_monitor,
  med_watch,
  disinfectant_wipes,
  first_aid_kit,
  oxygen_concentrator,
  ice_pack,
  cpr_mask,
  ultrasound,
  ventilator11,
  gloves,
  trauma_scissors,
  defibrillator13,
  stretcher15,
  face_mask16,
  emergency_blanket,
  iv_pump18,
  monitoring_system19,
  response_kit20,
  wound_care_kit21,
  triage_tent22,
  oxygen_mask23,
  ecg_machine24,
  rope25,
  hoke26,
  biometric_scanner27,
  infusion_stand28,
  respiratory_mask29,
  trauma_dressing30,
  fire_blanket31,
  sterile_needle32,
  water_purifier33,
  ultrasound_gel34,
  spinal_board35,
  defibrillator36,
  trauma_bag37,
  survival_tent38,
  blood_bag_warmer39,
  icePack40,
};

export const consultants = [
    [
        {
          "_id": "bba5u1",
          "name": "Wireless Bluetooth Thermometer",
          "image": ["thermometer1.jpg"],
          "description": "High-quality wireless thermometer with real-time temperature tracking.",
          "price": 199,
          "rating": 4.8,
          "category": "Medical Equipment",
          "subCategory": "Temperature Monitoring",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 50,
          "discount": 10,
          "brand": "MedTech",
          "seller": "Health Solutions Ltd.",
          "reviewsCount": 1200
        },
        {
          "_id": "bba5u2",
          "name": "Stainless Steel Medicine Storage Box",
          "image": ["medicine_box2.jpg"],
          "description": "Keeps your medicines organized and secure with temperature control.",
          "price": 25,
          "rating": 4.5,
          "category": "Medical Supplies",
          "subCategory": "Storage",
          "date": 1735664576821,
          "bestseller": false,
          "stock": 200,
          "discount": 5,
          "brand": "MediSafe",
          "seller": "Pharma Supplies Co.",
          "reviewsCount": 800
        },
        {
          "_id": "bba5u3",
          "name": "Blood Pressure Monitor",
          "image": ["bp_monitor3.jpg"],
          "description": "Portable device to monitor blood pressure with large LCD display.",
          "price": 60,
          "rating": 4.7,
          "category": "Medical Equipment",
          "subCategory": "Monitoring Devices",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 100,
          "discount": 15,
          "brand": "CarePlus",
          "seller": "Elite Medical Supplies",
          "reviewsCount": 1500
        },
        {
          "_id": "bba5u4",
          "name": "Smart Medical Watch",
          "image": ["med_watch4.jpg"],
          "description": "Track heart rate, blood oxygen levels, and receive emergency alerts.",
          "price": 150,
          "rating": 4.6,
          "category": "Medical Wearables",
          "subCategory": "Health Monitoring",
          "date": 1735664576821,
          "bestseller": false,
          "stock": 75,
          "discount": 12,
          "brand": "MedTrack",
          "seller": "TechHealth Retail",
          "reviewsCount": 1100
        },
        {
          "_id": "bba5u5",
          "name": "Disinfectant Wipes",
          "image": ["disinfectant_wipes5.jpg"],
          "description": "Alcohol-free, effective against germs and bacteria, perfect for hospitals.",
          "price": 30,
          "rating": 4.4,
          "category": "Medical Supplies",
          "subCategory": "Cleaning Products",
          "date": 1735664576821,
          "bestseller": false,
          "stock": 150,
          "discount": 8,
          "brand": "PureCare",
          "seller": "Healthy Med Co.",
          "reviewsCount": 600
        },
        {
          "_id": "bba5u6",
          "name": "Electric Oxygen Concentrator",
          "image": ["oxygen_concentrator6.jpg"],
          "description": "Portable oxygen concentrator with adjustable flow settings.",
          "price": 450,
          "rating": 4.5,
          "category": "Medical Equipment",
          "subCategory": "Oxygen Therapy",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 90,
          "discount": 10,
          "brand": "OxyPlus",
          "seller": "Respiratory Solutions",
          "reviewsCount": 950
        },
        {
          "_id": "bba5u7",
          "name": "First Aid Kit",
          "image": ["first_aid_kit7.jpg"],
          "description": "Comprehensive first aid kit for home, office, and outdoor use.",
          "price": 40,
          "rating": 4.9,
          "category": "Medical Supplies",
          "subCategory": "Emergency Kits",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 200,
          "discount": 5,
          "brand": "MedSafe",
          "seller": "Health Essentials",
          "reviewsCount": 1800
        },
        {
          "_id": "bba5u8",
          "name": "Therapeutic Ice Pack",
          "image": ["ice_pack8.jpg"],
          "description": "Reusable gel ice pack for pain relief and swelling reduction.",
          "price": 15,
          "rating": 4.3,
          "category": "Medical Supplies",
          "subCategory": "Pain Relief",
          "date": 1735664576821,
          "bestseller": false,
          "stock": 120,
          "discount": 10,
          "brand": "PainAway",
          "seller": "Health First Aid",
          "reviewsCount": 500
        },
        {
          "_id": "bba5u9",
          "name": "CPR Resuscitation Mask",
          "image": ["cpr_mask9.jpg"],
          "description": "Disposable mask for emergency CPR situations to prevent infection.",
          "price": 12,
          "rating": 4.7,
          "category": "Medical Supplies",
          "subCategory": "CPR Equipment",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 250,
          "discount": 5,
          "brand": "SafeBreath",
          "seller": "FirstAid Co.",
          "reviewsCount": 1000
        },
        {
          "_id": "bba5u10",
          "name": "Portable Ultrasound Device",
          "image": ["ultrasound10.jpg"],
          "description": "Compact ultrasound device for in-field diagnostics and assessments.",
          "price": 1200,
          "rating": 4.6,
          "category": "Medical Equipment",
          "subCategory": "Diagnostic Tools",
          "date": 1735664576821,
          "bestseller": false,
          "stock": 30,
          "discount": 8,
          "brand": "MedScan",
          "seller": "MedTech Supplies",
          "reviewsCount": 400
        },
        {
          "_id": "bba5u11",
          "name": "Portable Ventilator",
          "image": ["ventilator11.jpg"],
          "description": "Lightweight ventilator for emergency respiratory support.",
          "price": 850,
          "rating": 4.9,
          "category": "Medical Equipment",
          "subCategory": "Respiratory",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 50,
          "discount": 10,
          "brand": "AirFlow",
          "seller": "Respiratory Health Co.",
          "reviewsCount": 1400
        },
        {
          "_id": "bba5u12",
          "name": "Disposable Gloves",
          "image": ["gloves12.jpg"],
          "description": "Latex-free disposable gloves for healthcare workers and emergency responders.",
          "price": 10,
          "rating": 4.7,
          "category": "Medical Supplies",
          "subCategory": "Protective Gear",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 500,
          "discount": 2,
          "brand": "CareProtect",
          "seller": "SafeHands Supplies",
          "reviewsCount": 2200
        },
        {
          "_id": "bba5u13",
          "name": "Portable Defibrillator",
          "image": ["defibrillator13.jpg"],
          "description": "Compact defibrillator for emergency cardiac arrest situations.",
          "price": 1500,
          "rating": 5.0,
          "category": "Medical Equipment",
          "subCategory": "Cardiac Care",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 40,
          "discount": 10,
          "brand": "LifeSaver",
          "seller": "MedLife Solutions",
          "reviewsCount": 1700
        },
        {
          "_id": "bba5u14",
          "name": "Trauma Scissors",
          "image": ["trauma_scissors14.jpg"],
          "description": "Heavy-duty trauma scissors for cutting through clothing and medical tape.",
          "price": 25,
          "rating": 4.8,
          "category": "Medical Supplies",
          "subCategory": "First Aid Tools",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 300,
          "discount": 5,
          "brand": "EmergencyPro",
          "seller": "FirstAid Tools",
          "reviewsCount": 1300
        },
        {
          "_id": "bba5u15",
          "name": "Emergency Stretchers",
          "image": ["stretcher15.jpg"],
          "description": "Lightweight, foldable stretchers for safe patient transport.",
          "price": 120,
          "rating": 4.6,
          "category": "Medical Equipment",
          "subCategory": "Transport",
          "date": 1735664576821,
          "bestseller": false,
          "stock": 100,
          "discount": 12,
          "brand": "QuickTransport",
          "seller": "RescueCare Supplies",
          "reviewsCount": 900
        },
        {
          "_id": "bba5u16",
          "name": "Medical Face Masks",
          "image": ["face_mask16.jpg"],
          "description": "3-ply medical-grade face masks for high-risk environments.",
          "price": 15,
          "rating": 4.5,
          "category": "Medical Supplies",
          "subCategory": "Protective Gear",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 500,
          "discount": 5,
          "brand": "SafeCare",
          "seller": "Health Protective",
          "reviewsCount": 2500
        },
        {
          "_id": "bba5u17",
          "name": "Emergency Blanket",
          "image": ["emergency_blanket17.jpg"],
          "description": "Compact thermal blankets for warmth in disaster situations.",
          "price": 5,
          "rating": 4.8,
          "category": "Medical Supplies",
          "subCategory": "Emergency Gear",
          "date": 1735664576821,
          "bestseller": true,
          "stock": 1000,
          "discount": 2,
          "brand": "ThermoGuard",
          "seller": "Survival Gear Co.",
          "reviewsCount": 2200
        },
            {
              "_id": "bba5u18",
              "name": "Portable IV Infusion Pump",
              "image": ["iv_pump18.jpg"],
              "description": "Portable IV pump for administering fluids in emergency situations.",
              "price": 750,
              "rating": 4.9,
              "category": "Medical Equipment",
              "subCategory": "Infusion Therapy",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 40,
              "discount": 10,
              "brand": "MedFlow",
              "seller": "IV Health Solutions",
              "reviewsCount": 1100
            },
            {
              "_id": "bba5u19",
              "name": "Patient Monitoring System",
              "image": ["monitoring_system19.jpg"],
              "description": "Comprehensive monitoring system for tracking vital signs in critical care.",
              "price": 2500,
              "rating": 4.8,
              "category": "Medical Equipment",
              "subCategory": "Monitoring Devices",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 25,
              "discount": 5,
              "brand": "VitalTech",
              "seller": "MedCare Systems",
              "reviewsCount": 600
            },
            {
              "_id": "bba5u20",
              "name": "Disaster Response Kit",
              "image": ["response_kit20.jpg"],
              "description": "Comprehensive kit with medical supplies for disaster response teams.",
              "price": 200,
              "rating": 4.7,
              "category": "Emergency Supplies",
              "subCategory": "Response Kits",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 150,
              "discount": 15,
              "brand": "RescueCare",
              "seller": "Emergency Response Co.",
              "reviewsCount": 900
            },
            {
              "_id": "bba5u21",
              "name": "Wound Care Kit",
              "image": ["wound_care_kit21.jpg"],
              "description": "Complete wound care kit for field treatment of injuries.",
              "price": 45,
              "rating": 4.6,
              "category": "Medical Supplies",
              "subCategory": "Wound Care",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 250,
              "discount": 10,
              "brand": "FirstAid Plus",
              "seller": "HealthFirst Supplies",
              "reviewsCount": 1200
            },
            {
              "_id": "bba5u22",
              "name": "Medical Triage Tent",
              "image": ["triage_tent22.jpg"],
              "description": "Portable triage tent for medical treatment in outdoor emergency environments.",
              "price": 1500,
              "rating": 4.7,
              "category": "Emergency Supplies",
              "subCategory": "Shelters",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 30,
              "discount": 10,
              "brand": "QuickCare",
              "seller": "Emergency Shelters Co.",
              "reviewsCount": 300
            },
            {
              "_id": "bba5u23",
              "name": "Medical Oxygen Mask",
              "image": ["oxygen_mask23.jpg"],
              "description": "High-flow oxygen mask for emergency respiratory support.",
              "price": 20,
              "rating": 4.5,
              "category": "Medical Supplies",
              "subCategory": "Respiratory Care",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 400,
              "discount": 5,
              "brand": "OxyPro",
              "seller": "AirCare Medical",
              "reviewsCount": 700
            },
            {
              "_id": "bba5u24",
              "name": "Portable ECG Machine",
              "image": ["ecg_machine24.jpg"],
              "description": "Compact ECG machine for emergency heart rate monitoring.",
              "price": 1200,
              "rating": 4.9,
              "category": "Medical Equipment",
              "subCategory": "Cardiac Care",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 50,
              "discount": 8,
              "brand": "CardioTech",
              "seller": "HeartCare Solutions",
              "reviewsCount": 400
            },
            {
              "_id": "bba5u25",
              "name": "rope",
              "image": ["rope25.jpg"],
              "description": "Durable stretcher for patient transport in ambulances.",
              "price": 35,
              "rating": 4.8,
              "category": "Medical Equipment",
              "subCategory": "Transport",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 75,
              "discount": 10,
              "brand": "RescuePro",
              "seller": "FirstResponder Equipments",
              "reviewsCount": 1300
            },
            {
              "_id": "bba5u26",
              "name": "hoke",
              "image": ["hoke26.jpg"],
              "description": "Fully equipped emergency vehicle for disaster response.",
              "price": 50,
              "rating": 5.0,
              "category": "Emergency Equipment",
              "subCategory": "Transport",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 5,
              "discount": 5,
              "brand": "RescueMobile",
              "seller": "Disaster Response Vehicles",
              "reviewsCount": 200
            },
            {
              "_id": "bba5u27",
              "name": "Portable Biometric Patient Scanner",
              "image": ["biometric_scanner27.jpg"],
              "description": "Portable scanner for biometric data collection and medical assessments.",
              "price": 2500,
              "rating": 4.7,
              "category": "Medical Equipment",
              "subCategory": "Diagnostic Tools",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 20,
              "discount": 10,
              "brand": "BioTrack",
              "seller": "Diagnostic Equipment Co.",
              "reviewsCount": 500
            },
            {
              "_id": "bba5u28",
              "name": "Portable Infusion Stand",
              "image": ["infusion_stand28.jpg"],
              "description": "Adjustable portable stand for administering IV treatments.",
              "price": 75,
              "rating": 4.6,
              "category": "Medical Equipment",
              "subCategory": "Infusion Therapy",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 100,
              "discount": 5,
              "brand": "MedStand",
              "seller": "HealthEquip Co.",
              "reviewsCount": 800
            },
            {
              "_id": "bba5u29",
              "name": "Emergency Respiratory Mask",
              "image": ["respiratory_mask29.jpg"],
              "description": "Full-face respirator mask for emergency air filtration.",
              "price": 45,
              "rating": 4.4,
              "category": "Medical Supplies",
              "subCategory": "Protective Gear",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 150,
              "discount": 8,
              "brand": "RespiraSafe",
              "seller": "Respiratory Health Co.",
              "reviewsCount": 600
            },
            {
              "_id": "bba5u30",
              "name": "Trauma Dressing",
              "image": ["trauma_dressing30.jpg"],
              "description": "Large, sterile trauma dressing for severe wounds.",
              "price": 18,
              "rating": 4.7,
              "category": "Medical Supplies",
              "subCategory": "First Aid",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 500,
              "discount": 5,
              "brand": "CareFirst",
              "seller": "Health Care Solutions",
              "reviewsCount": 1300
            },
            {
              "_id": "bba5u31",
              "name": "Emergency Fire Blanket",
              "image": ["fire_blanket31.jpg"],
              "description": "Compact and fire-resistant emergency blanket for fire safety.",
              "price": 25,
              "rating": 4.6,
              "category": "Emergency Gear",
              "subCategory": "Fire Safety",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 200,
              "discount": 10,
              "brand": "FireGuard",
              "seller": "Safety Gear Co.",
              "reviewsCount": 850
            },
            {
              "_id": "bba5u32",
              "name": "Sterile Needle Pack",
              "image": ["sterile_needle32.jpg"],
              "description": "Pack of sterile needles for emergency medical procedures.",
              "price": 10,
              "rating": 4.8,
              "category": "Medical Supplies",
              "subCategory": "Injection Tools",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 1000,
              "discount": 5,
              "brand": "MedSteril",
              "seller": "Medical Supplies Co.",
              "reviewsCount": 1500
            },
            {
              "_id": "bba5u33",
              "name": "Emergency Water Purifier",
              "image": ["water_purifier33.jpg"],
              "description": "Portable water purifier for safe drinking water in emergencies.",
              "price": 55,
              "rating": 4.4,
              "category": "Emergency Gear",
              "subCategory": "Water Safety",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 250,
              "discount": 5,
              "brand": "PureSafe",
              "seller": "Survival Gear Co.",
              "reviewsCount": 1100
            },
            {
              "_id": "bba5u34",
              "name": "Portable Ultrasound Gel",
              "image": ["ultrasound_gel34.jpg"],
              "description": "Specialized gel for ultrasound imaging in field environments.",
              "price": 30,
              "rating": 4.6,
              "category": "Medical Supplies",
              "subCategory": "Diagnostic Tools",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 350,
              "discount": 10,
              "brand": "UltraScan",
              "seller": "MedEquip Supplies",
              "reviewsCount": 400
            },
            {
              "_id": "bba5u35",
              "name": "Emergency Spinal Board",
              "image": ["spinal_board35.jpg"],
              "description": "Rigid spinal board for safe patient transportation during emergencies.",
              "price": 220,
              "rating": 4.8,
              "category": "Medical Equipment",
              "subCategory": "Transport",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 50,
              "discount": 5,
              "brand": "SpinalCare",
              "seller": "Rescue Equipments Co.",
              "reviewsCount": 950
            },
            {
              "_id": "bba5u36",
              "name": "Portable Defibrillator",
              "image": ["defibrillator36.jpg"],
              "description": "Compact, portable defibrillator for heart emergency response.",
              "price": 2200,
              "rating": 4.9,
              "category": "Medical Equipment",
              "subCategory": "Cardiac Care",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 30,
              "discount": 10,
              "brand": "LifeSaver",
              "seller": "Emergency Medical Co.",
              "reviewsCount": 500
            },
            {
              "_id": "bba5u37",
              "name": "Emergency Trauma Bag",
              "image": ["trauma_bag37.jpg"],
              "description": "All-in-one trauma bag equipped with essential emergency medical tools.",
              "price": 100,
              "rating": 4.7,
              "category": "Emergency Supplies",
              "subCategory": "Trauma Kits",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 400,
              "discount": 15,
              "brand": "CareTrauma",
              "seller": "Medical Gear Co.",
              "reviewsCount": 1200
            },
            {
              "_id": "bba5u38",
              "name": "Survival Medical Tent",
              "image": ["survival_tent38.jpg"],
              "description": "Weather-resistant medical tent for field hospitals in disaster zones.",
              "price": 3500,
              "rating": 4.8,
              "category": "Emergency Supplies",
              "subCategory": "Shelters",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 10,
              "discount": 5,
              "brand": "TentCare",
              "seller": "Disaster Shelters Co.",
              "reviewsCount": 200
            },
            {
              "_id": "bba5u39",
              "name": "Portable Blood Bag Warmer",
              "image": ["blood_bag_warmer39.jpg"],
              "description": "Portable device to keep blood bags at optimal temperatures in emergencies.",
              "price": 500,
              "rating": 4.7,
              "category": "Medical Equipment",
              "subCategory": "Blood Storage",
              "date": 1735664576821,
              "bestseller": false,
              "stock": 25,
              "discount": 8,
              "brand": "BloodSafe",
              "seller": "MedTransport Co.",
              "reviewsCount": 350
            },
            {
              "_id": "bba5u40",
              "name": "ice Pack",
              "image": ["icePack40.jpg"],
              "description": "Portable first aid kit for quick access to emergency supplies.",
              "price": 15,
              "rating": 4.5,
              "category": "Medical Supplies",
              "subCategory": "First Aid Kits",
              "date": 1735664576821,
              "bestseller": true,
              "stock": 500,
              "discount": 10,
              "brand": "CareBox",
              "seller": "FirstAid Health",
              "reviewsCount": 1000
            }
          
          
      ]
  
];
